// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OzmenZimparaMarket.Infrastructure.Veritabani;

#nullable disable

namespace OzmenZimparaMarket.Infrastructure.Veritabani.Migrations
{
    [DbContext(typeof(OzmenZimparaMarketDbContext))]
    [Migration("20260919035355_UrunKoduOpsiyonel")]
    partial class UrunKoduOpsiyonel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.FirmaGenelBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AcikAdres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GoogleHaritaBaglantisi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("GoogleHaritaGommeBaglantisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Hakkimizda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IletisimNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("KalitePolitikamiz")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kvkk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Misyonumuz")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SirketAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Stratejimiz")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vizyonumuz")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhatsappNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("FirmaGenelBilgileri", (string)null);
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AnaSayfadaGosterilsinMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GorselYolu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("SeoAciklamasi")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SeoBasligi")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("SeoUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<int?>("UstKategoriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeoUrl")
                        .IsUnique();

                    b.HasIndex("UstKategoriId");

                    b.HasIndex("AktifMi", "SiraNo");

                    b.HasIndex("AnaSayfadaGosterilsinMi", "AktifMi");

                    b.ToTable("Kategoriler", (string)null);
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.PanelKullanicisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("PanelKullanicilari", (string)null);
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DetayliAciklama")
                        .HasColumnType("longtext");

                    b.Property<string>("GorselYolu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("KisaAciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("OneCikanMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SatisBirimi")
                        .HasColumnType("int");

                    b.Property<string>("SeoAciklamasi")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SeoBasligi")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("SeoUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UrunKodu")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("SeoUrl")
                        .IsUnique();

                    b.HasIndex("UrunKodu")
                        .IsUnique();

                    b.HasIndex("KategoriId", "AktifMi", "SiraNo");

                    b.HasIndex("OneCikanMi", "AktifMi", "SiraNo");

                    b.ToTable("Urunler", (string)null);
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.UrunDetayTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CokluDegerMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DetayAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("FiltredeGosterilsinMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SepetteSecilebilirMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetayAdi")
                        .IsUnique();

                    b.HasIndex("AktifMi", "SiraNo");

                    b.HasIndex("FiltredeGosterilsinMi", "AktifMi", "SiraNo");

                    b.HasIndex("SepetteSecilebilirMi", "AktifMi", "SiraNo");

                    b.ToTable("UrunDetayTanimlari", (string)null);
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.UrunDetayi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DetayDegeri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<int>("UrunDetayTanimiId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UrunDetayTanimiId");

                    b.HasIndex("UrunId");

                    b.HasIndex("UrunId", "AktifMi", "SiraNo");

                    b.HasIndex("UrunId", "UrunDetayTanimiId", "DetayDegeri")
                        .IsUnique();

                    b.ToTable("UrunDetaylari", (string)null);
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.Kategori", b =>
                {
                    b.HasOne("OzmenZimparaMarket.Domain.Entityler.Kategori", "UstKategori")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("UstKategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UstKategori");
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.Urun", b =>
                {
                    b.HasOne("OzmenZimparaMarket.Domain.Entityler.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.UrunDetayi", b =>
                {
                    b.HasOne("OzmenZimparaMarket.Domain.Entityler.UrunDetayTanimi", "UrunDetayTanimi")
                        .WithMany("UrunDetaylari")
                        .HasForeignKey("UrunDetayTanimiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OzmenZimparaMarket.Domain.Entityler.Urun", "Urun")
                        .WithMany("UrunDetaylari")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");

                    b.Navigation("UrunDetayTanimi");
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.Kategori", b =>
                {
                    b.Navigation("AltKategoriler");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.Urun", b =>
                {
                    b.Navigation("UrunDetaylari");
                });

            modelBuilder.Entity("OzmenZimparaMarket.Domain.Entityler.UrunDetayTanimi", b =>
                {
                    b.Navigation("UrunDetaylari");
                });
#pragma warning restore 612, 618
        }
    }
}
